version: '3.6'

volumes:
  letsencrypt:
    external: true

services:
  redis:
    image: redis:6.0.8-alpine
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./target/data:/data
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'
    restart: unless-stopped
  cibulb:
    container_name: cibulb
    build: .
    ports:
      - 8080-8081:8080-8081
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - type: volume
        source: letsencrypt
        target: /le-ssl
    depends_on:
      - redis
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'
    restart: unless-stopped
